In [1]:
!pip install pydeseq2

Collecting pydeseq2
  Downloading pydeseq2-0.5.4-py3-none-any.whl.metadata (9.3 kB)
Collecting anndata>=0.11.0 (from pydeseq2)
  Downloading anndata-0.12.16-py3-none-any.whl.metadata (9.9 kB)
Collecting formulaic-contrasts>=0.2.0 (from pydeseq2)
  Downloading formulaic_contrasts-1.0.0-py3-none-any.whl.metadata (6.5 kB)
Collecting formulaic>=1.0.2 (from pydeseq2)
  Downloading formulaic-1.2.1-py3-none-any.whl.metadata (7.0 kB)
Requirement already satisfied: matplotlib>=3.9.0 in /usr/local/lib/python3.12/dist-packages (from pydeseq2) (3.10.0)
Requirement already satisfied: numpy>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from pydeseq2) (2.0.2)
Requirement already satisfied: pandas>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from pydeseq2) (2.2.2)
Requirement already satisfied: scikit-learn>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from pydeseq2) (1.6.1)
Requirement already satisfied: scipy>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from pydeseq2) (1.16.3)
Collecting array-api-compat>=1.7.1 (from anndata>=0.11.0->pydeseq2)
  Downloading array_api_compat-1.14.0-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: h5py>=3.8 in /usr/local/lib/python3.12/dist-packages (from anndata>=0.11.0->pydeseq2) (3.16.0)
Collecting legacy-api-wrap (from anndata>=0.11.0->pydeseq2)
  Downloading legacy_api_wrap-1.5-py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: natsort in /usr/local/lib/python3.12/dist-packages (from anndata>=0.11.0->pydeseq2) (8.4.0)
Requirement already satisfied: packaging>=24.2 in /usr/local/lib/python3.12/dist-packages (from anndata>=0.11.0->pydeseq2) (26.2)
Collecting scverse-misc>=0.0.3 (from anndata>=0.11.0->pydeseq2)
  Downloading scverse_misc-0.0.7-py3-none-any.whl.metadata (4.5 kB)
Collecting zarr!=3.0.*,>=2.18.7 (from anndata>=0.11.0->pydeseq2)
  Downloading zarr-3.2.1-py3-none-any.whl.metadata (8.7 kB)
Collecting interface-meta>=1.2.0 (from formulaic>=1.0.2->pydeseq2)
  Downloading interface_meta-2.0.1-py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: narwhals>=1.17 in /usr/local/lib/python3.12/dist-packages (from formulaic>=1.0.2->pydeseq2) (2.21.2)
Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.12/dist-packages (from formulaic>=1.0.2->pydeseq2) (4.15.0)
Requirement already satisfied: wrapt>=1.0 in /usr/local/lib/python3.12/dist-packages (from formulaic>=1.0.2->pydeseq2) (2.2.0)
Collecting session-info (from formulaic-contrasts>=0.2.0->pydeseq2)
  Downloading session_info-1.0.1-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.9.0->pydeseq2) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.9.0->pydeseq2) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.9.0->pydeseq2) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.9.0->pydeseq2) (1.5.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.9.0->pydeseq2) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.9.0->pydeseq2) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.9.0->pydeseq2) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.0->pydeseq2) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.0->pydeseq2) (2026.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.4.0->pydeseq2) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.4.0->pydeseq2) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.9.0->pydeseq2) (1.17.0)
Collecting session-info2 (from scverse-misc>=0.0.3->anndata>=0.11.0->pydeseq2)
  Downloading session_info2-0.4.1-py3-none-any.whl.metadata (2.5 kB)
Collecting donfig>=0.8 (from zarr!=3.0.*,>=2.18.7->anndata>=0.11.0->pydeseq2)
  Downloading donfig-0.8.1.post1-py3-none-any.whl.metadata (5.0 kB)
Requirement already satisfied: google-crc32c>=1.5 in /usr/local/lib/python3.12/dist-packages (from zarr!=3.0.*,>=2.18.7->anndata>=0.11.0->pydeseq2) (1.8.0)
Collecting numcodecs>=0.14 (from zarr!=3.0.*,>=2.18.7->anndata>=0.11.0->pydeseq2)
  Downloading numcodecs-0.16.5-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (3.4 kB)
Collecting stdlib_list (from session-info->formulaic-contrasts>=0.2.0->pydeseq2)
  Downloading stdlib_list-0.12.0-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from donfig>=0.8->zarr!=3.0.*,>=2.18.7->anndata>=0.11.0->pydeseq2) (6.0.3)
Downloading pydeseq2-0.5.4-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.6/45.6 kB 2.4 MB/s eta 0:00:00
Downloading anndata-0.12.16-py3-none-any.whl (175 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.3/175.3 kB 6.7 MB/s eta 0:00:00
Downloading formulaic-1.2.1-py3-none-any.whl (117 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.3/117.3 kB 9.6 MB/s eta 0:00:00
Downloading formulaic_contrasts-1.0.0-py3-none-any.whl (10 kB)
Downloading array_api_compat-1.14.0-py3-none-any.whl (60 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.1/60.1 kB 4.6 MB/s eta 0:00:00
Downloading interface_meta-2.0.1-py3-none-any.whl (15 kB)
Downloading scverse_misc-0.0.7-py3-none-any.whl (13 kB)
Downloading zarr-3.2.1-py3-none-any.whl (319 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 319.6/319.6 kB 13.5 MB/s eta 0:00:00
Downloading legacy_api_wrap-1.5-py3-none-any.whl (10 kB)
Downloading session_info-1.0.1-py3-none-any.whl (9.1 kB)
Downloading donfig-0.8.1.post1-py3-none-any.whl (21 kB)
Downloading numcodecs-0.16.5-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (9.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.2/9.2 MB 89.8 MB/s eta 0:00:00
Downloading session_info2-0.4.1-py3-none-any.whl (17 kB)
Downloading stdlib_list-0.12.0-py3-none-any.whl (87 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.6/87.6 kB 6.9 MB/s eta 0:00:00
Installing collected packages: stdlib_list, session-info2, numcodecs, legacy-api-wrap, interface-meta, donfig, array-api-compat, zarr, session-info, scverse-misc, formulaic, anndata, formulaic-contrasts, pydeseq2
Successfully installed anndata-0.12.16 array-api-compat-1.14.0 donfig-0.8.1.post1 formulaic-1.2.1 formulaic-contrasts-1.0.0 interface-meta-2.0.1 legacy-api-wrap-1.5 numcodecs-0.16.5 pydeseq2-0.5.4 scverse-misc-0.0.7 session-info-1.0.1 session-info2-0.4.1 stdlib_list-0.12.0 zarr-3.2.1

In [2]:
import numpy as np
import pandas as pd
from pydeseq2.dds import DeseqDataSet
from pydeseq2.ds import DeseqStats

In [3]:
np.random.seed(42)

n_genes = 1000
n_samples = 20

# Criando matriz de contagem (inteiros)
counts = np.random.poisson(lam=50, size=(n_samples, n_genes))

# Criando DataFrame
counts_df = pd.DataFrame(
    counts,
    columns=[f"gene_{i}" for i in range(n_genes)]
)

# Criando metadados (duas condições)
conditions = ["control"] * 10 + ["treated"] * 10

metadata = pd.DataFrame({
    "condition": conditions
})

counts_df.head()

,gene_0,gene_1,gene_2,gene_3,gene_4,gene_5,gene_6,gene_7,gene_8,gene_9,...,gene_990,gene_991,gene_992,gene_993,gene_994,gene_995,gene_996,gene_997,gene_998,gene_999
0,47,55,42,52,58,43,46,49,52,45,...,48,60,42,53,47,48,54,47,54,50
1,48,42,56,45,46,52,68,48,51,51,...,59,50,40,36,46,42,40,40,61,57
2,38,44,42,61,60,45,47,51,54,46,...,50,46,55,53,55,59,45,50,47,39
3,43,44,56,52,50,51,50,57,41,63,...,40,52,61,39,50,47,53,50,67,50
4,51,47,38,45,51,37,53,49,51,46,...,39,60,61,45,60,51,51,57,61,56

In [4]:
from pydeseq2.dds import DeseqDataSet

dds = DeseqDataSet(
    counts=counts_df,
    metadata=metadata,   # <-- aqui está a correção
    design_factors="condition"
)

/usr/lib/python3.12/functools.py:912: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)
/tmp/ipykernel_493/2943200646.py:3: DeprecationWarning: design_factors is deprecated and will soon be removed.Please consider providing a formulaic formula using the design argumentinstead.
  dds = DeseqDataSet(

In [5]:
dds.deseq2()

Using None as control genes, passed at DeseqDataSet initialization

Fitting size factors...
... done in 0.01 seconds.

Fitting dispersions...
... done in 1.93 seconds.

Fitting dispersion trend curve...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 1.26 seconds.

Fitting LFCs...
... done in 0.64 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 0 outlier genes.

In [6]:
stat_res = DeseqStats(
    dds,
    contrast=("condition", "treated", "control")
)

In [7]:
stat_res.summary()

Running Wald tests...

Log2 fold change & Wald test p-value: condition treated vs control
           baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
gene_0    46.652329        0.113214  0.106969  1.058379  0.289883  0.988532
gene_1    49.336776       -0.008885  0.106403 -0.083502  0.933452  0.988532
gene_2    47.698949        0.023448  0.110464  0.212270  0.831897  0.988532
gene_3    51.437087       -0.019454  0.102348 -0.190082  0.849244  0.988532
gene_4    51.834349       -0.024787  0.101398 -0.244450  0.806882  0.988532
...             ...             ...       ...       ...       ...       ...
gene_995  49.335106        0.049117  0.104950  0.468006  0.639781  0.988532
gene_996  50.191664        0.028540  0.102763  0.277725  0.781224  0.988532
gene_997  51.280856       -0.067115  0.103916 -0.645860  0.518370  0.988532
gene_998  54.216799       -0.071233  0.101369 -0.702707  0.482238  0.988532
gene_999  48.103773       -0.048102  0.105915 -0.454158  0.649715  0.988532

[1000 rows x 6 columns]

... done in 0.29 seconds.

In [8]:
stat_res.run_wald_test()
stat_res.summary()

Running Wald tests...

Log2 fold change & Wald test p-value: condition treated vs control
           baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
gene_0    46.652329        0.113214  0.106969  1.058379  0.289883  0.988532
gene_1    49.336776       -0.008885  0.106403 -0.083502  0.933452  0.988532
gene_2    47.698949        0.023448  0.110464  0.212270  0.831897  0.988532
gene_3    51.437087       -0.019454  0.102348 -0.190082  0.849244  0.988532
gene_4    51.834349       -0.024787  0.101398 -0.244450  0.806882  0.988532
...             ...             ...       ...       ...       ...       ...
gene_995  49.335106        0.049117  0.104950  0.468006  0.639781  0.988532
gene_996  50.191664        0.028540  0.102763  0.277725  0.781224  0.988532
gene_997  51.280856       -0.067115  0.103916 -0.645860  0.518370  0.988532
gene_998  54.216799       -0.071233  0.101369 -0.702707  0.482238  0.988532
gene_999  48.103773       -0.048102  0.105915 -0.454158  0.649715  0.988532

[1000 rows x 6 columns]

... done in 0.31 seconds.

**Essa tabela mostra quais genes mudaram, quanto mudaram e se essa mudança é estatisticamente confiável.**

In [9]:
results_df = stat_res.results_df
results_df.head()

         baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
gene_0  46.652329        0.113214  0.106969  1.058379  0.289883  0.988532
gene_1  49.336776       -0.008885  0.106403 -0.083502  0.933452  0.988532
gene_2  47.698949        0.023448  0.110464  0.212270  0.831897  0.988532
gene_3  51.437087       -0.019454  0.102348 -0.190082  0.849244  0.988532
gene_4  51.834349       -0.024787  0.101398 -0.244450  0.806882  0.988532